server:
  port: 8855
spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbcs:mysql://122.9.33.79:3307/mentorselection?serverTimezone=Asia/Shanghai
    username: root
    password: 1157
    pool:
      enabled: true
      initial-size: 1
      validation-query: select 1
      max-life-time: 30000

  jackson:
    default-property-inclusion: non_null
---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbcs:mysql://${dhost}/mentorselection?serverTimezone=Asia/Shanghai
    username: ${dusername}
    password: ${dpassword}
    pool:
      max-size: 200