server:
  port: 8855
spring:
  r2dbc:
    url: r2dbcs:mysql://122.9.33.79:3308/mentorselection?serverTimezone=Asia/Shanghai&&SSL=false&sslMode=DISABLED
    username: root
    password: 123456
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update